
#include "../../types/types.h"

struct
{
    char symbol[3];
    oxistates_t states;
}oxistates_table[NUMBER_OF_ELEMENTS] = 
{
	{ .symbol = "H", .states.n = 2, .states.states = {1, -1} },
	{ .symbol = "He", .states.n = 1, .states.states = {0} },
	{ .symbol = "Li", .states.n = 1, .states.states = {1} },
	{ .symbol = "Be", .states.n = 1, .states.states = {2} },
	{ .symbol = "B", .states.n = 1, .states.states = {3} },
	{ .symbol = "C", .states.n = 3, .states.states = {4, 2, -4} },
	{ .symbol = "N", .states.n = 8, .states.states = {5, 4, 3, 2, -3, 1, -2, -1} },
	{ .symbol = "O", .states.n = 1, .states.states = {-2} },
	{ .symbol = "F", .states.n = 1, .states.states = {-1} },
	{ .symbol = "Ne", .states.n = 1, .states.states = {0} },
	{ .symbol = "Na", .states.n = 1, .states.states = {1} },
	{ .symbol = "Mg", .states.n = 1, .states.states = {2} },
	{ .symbol = "Al", .states.n = 1, .states.states = {3} },
	{ .symbol = "Si", .states.n = 3, .states.states = {4, -4, 2} },
	{ .symbol = "P", .states.n = 3, .states.states = {5, 3, -3} },
	{ .symbol = "S", .states.n = 4, .states.states = {6, 4, 2, -2} },
	{ .symbol = "Cl", .states.n = 5, .states.states = {7, 5, 3, 1, -1} },
	{ .symbol = "Ar", .states.n = 1, .states.states = {0} },
	{ .symbol = "K", .states.n = 1, .states.states = {1} },
	{ .symbol = "Ca", .states.n = 1, .states.states = {2} },
	{ .symbol = "Sc", .states.n = 1, .states.states = {3} },
	{ .symbol = "Ti", .states.n = 3, .states.states = {4, 3, 2} },
	{ .symbol = "V", .states.n = 4, .states.states = {5, 4, 3, 2} },
	{ .symbol = "Cr", .states.n = 3, .states.states = {6, 3, 2} },
	{ .symbol = "Mn", .states.n = 5, .states.states = {7, 6, 4, 3, 2} },
	{ .symbol = "Fe", .states.n = 2, .states.states = {3, 2} },
	{ .symbol = "Co", .states.n = 2, .states.states = {3, 2} },
	{ .symbol = "Ni", .states.n = 2, .states.states = {3, 2} },
	{ .symbol = "Cu", .states.n = 2, .states.states = {2, 1} },
	{ .symbol = "Zn", .states.n = 1, .states.states = {2} },
	{ .symbol = "Ga", .states.n = 1, .states.states = {3} },
	{ .symbol = "Ge", .states.n = 2, .states.states = {4, 2} },
	{ .symbol = "As", .states.n = 3, .states.states = {5, 3, -3} },
	{ .symbol = "Se", .states.n = 3, .states.states = {6, 4, -2} },
	{ .symbol = "Br", .states.n = 5, .states.states = {7, 5, 3, 1, -1} },
	{ .symbol = "Kr", .states.n = 1, .states.states = {0} },
	{ .symbol = "Rb", .states.n = 1, .states.states = {1} },
	{ .symbol = "Sr", .states.n = 1, .states.states = {2} },
	{ .symbol = "Y", .states.n = 1, .states.states = {3} },
	{ .symbol = "Zr", .states.n = 1, .states.states = {4} },
	{ .symbol = "Nb", .states.n = 2, .states.states = {5, 3} },
	{ .symbol = "Mo", .states.n = 5, .states.states = {6, 5, 4, 3, 2} },
	{ .symbol = "Tc", .states.n = 3, .states.states = {7, 6, 4} },
	{ .symbol = "Ru", .states.n = 5, .states.states = {8, 6, 4, 3, 2} },
	{ .symbol = "Rh", .states.n = 5, .states.states = {5, 4, 3, 2, 1} },
	{ .symbol = "Pd", .states.n = 2, .states.states = {4, 2} },
	{ .symbol = "Ag", .states.n = 2, .states.states = {2, 1} },
	{ .symbol = "Cd", .states.n = 1, .states.states = {2} },
	{ .symbol = "In", .states.n = 1, .states.states = {3} },
	{ .symbol = "Sn", .states.n = 2, .states.states = {4, 2} },
	{ .symbol = "Sb", .states.n = 3, .states.states = {5, 3, -3} },
	{ .symbol = "Te", .states.n = 3, .states.states = {6, 4, -2} },
	{ .symbol = "I", .states.n = 4, .states.states = {7, 5, 1, -1} },
	{ .symbol = "Xe", .states.n = 1, .states.states = {0} },
	{ .symbol = "Cs", .states.n = 1, .states.states = {1} },
	{ .symbol = "Ba", .states.n = 1, .states.states = {2} },
	{ .symbol = "La", .states.n = 1, .states.states = {3} },
	{ .symbol = "Ce", .states.n = 2, .states.states = {4, 3} },
	{ .symbol = "Pr", .states.n = 2, .states.states = {4, 3} },
	{ .symbol = "Nd", .states.n = 1, .states.states = {3} },
	{ .symbol = "Pm", .states.n = 1, .states.states = {3} },
	{ .symbol = "Sm", .states.n = 2, .states.states = {3, 2} },
	{ .symbol = "Eu", .states.n = 2, .states.states = {3, 2} },
	{ .symbol = "Gd", .states.n = 1, .states.states = {3} },
	{ .symbol = "Tb", .states.n = 2, .states.states = {4, 3} },
	{ .symbol = "Dy", .states.n = 1, .states.states = {3} },
	{ .symbol = "Ho", .states.n = 1, .states.states = {3} },
	{ .symbol = "Er", .states.n = 1, .states.states = {3} },
	{ .symbol = "Tm", .states.n = 2, .states.states = {3, 2} },
	{ .symbol = "Yb", .states.n = 2, .states.states = {3, 2} },
	{ .symbol = "Lu", .states.n = 1, .states.states = {3} },
	{ .symbol = "Hf", .states.n = 1, .states.states = {4} },
	{ .symbol = "Ta", .states.n = 1, .states.states = {5} },
	{ .symbol = "W", .states.n = 6, .states.states = {6, 5, 4, 3, 2, 0} },
	{ .symbol = "Re", .states.n = 5, .states.states = {5, 4, 3, 2, -1} },
	{ .symbol = "Os", .states.n = 7, .states.states = {8, 6, 4, 3, 2, 0, -2} },
	{ .symbol = "Ir", .states.n = 7, .states.states = {6, 4, 3, 2, 1, 0, -1} },
	{ .symbol = "Pt", .states.n = 3, .states.states = {4, 2, 0} },
	{ .symbol = "Au", .states.n = 2, .states.states = {3, 1} },
	{ .symbol = "Hg", .states.n = 2, .states.states = {2, 1} },
	{ .symbol = "Tl", .states.n = 2, .states.states = {3, 1} },
	{ .symbol = "Pb", .states.n = 2, .states.states = {4, 2} },
	{ .symbol = "Bi", .states.n = 2, .states.states = {5, 3} },
	{ .symbol = "Po", .states.n = 3, .states.states = {6, 4, 2} },
	{ .symbol = "At", .states.n = 5, .states.states = {7, 5, 3, 1, -1} },
	{ .symbol = "Rn", .states.n = 1, .states.states = {} },
	{ .symbol = "Fr", .states.n = 1, .states.states = {2} },
	{ .symbol = "Ra", .states.n = 1, .states.states = {2} },
	{ .symbol = "Ac", .states.n = 1, .states.states = {3} },
	{ .symbol = "Th", .states.n = 1, .states.states = {4} },
	{ .symbol = "Pa", .states.n = 2, .states.states = {5, 4} },
	{ .symbol = "U", .states.n = 4, .states.states = {6, 5, 4, 3} },
	{ .symbol = "Np", .states.n = 4, .states.states = {6, 5, 4, 3} },
	{ .symbol = "Pu", .states.n = 4, .states.states = {6, 5, 4, 3} },
	{ .symbol = "Am", .states.n = 4, .states.states = {6, 5, 4, 3} },
	{ .symbol = "Cm", .states.n = 2, .states.states = {4, 3} },
	{ .symbol = "Bk", .states.n = 2, .states.states = {4, 3} },
	{ .symbol = "Cf", .states.n = 2, .states.states = {4, 3} },
	{ .symbol = "Es", .states.n = 1, .states.states = {3} },
	{ .symbol = "Fm", .states.n = 1, .states.states = {3} },
	{ .symbol = "Md", .states.n = 1, .states.states = {3} },
	{ .symbol = "No", .states.n = 2, .states.states = {3, 2} },
	{ .symbol = "Lr", .states.n = 1, .states.states = {3} },
	{ .symbol = "Rf", .states.n = 0, .states.states = {} },
	{ .symbol = "Db", .states.n = 0, .states.states = {} },
	{ .symbol = "Sg", .states.n = 0, .states.states = {} },
	{ .symbol = "Bh", .states.n = 0, .states.states = {} },
	{ .symbol = "Hs", .states.n = 0, .states.states = {} },
	{ .symbol = "Mt", .states.n = 0, .states.states = {} },
	{ .symbol = "Ds", .states.n = 0, .states.states = {} },
	{ .symbol = "Rg", .states.n = 0, .states.states = {} },
	{ .symbol = "Cn", .states.n = 0, .states.states = {} },
	{ .symbol = "Nh", .states.n = 0, .states.states = {} },
	{ .symbol = "Fl", .states.n = 0, .states.states = {} },
	{ .symbol = "Mc", .states.n = 0, .states.states = {} },
	{ .symbol = "Lv", .states.n = 0, .states.states = {} },
	{ .symbol = "Ts", .states.n = 0, .states.states = {} },
	{ .symbol = "Og", .states.n = 0, .states.states = {} },
};
