
#include "../../types/types.h"

struct
{
    oxistates_t states;
}oxistates_table[NUMBER_OF_ELEMENTS] = 
{
	{ .states.n = 2, .states.states = {1, -1} },
	{ .states.n = 1, .states.states = {0} },
	{ .states.n = 1, .states.states = {1} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 3, .states.states = {4, 2, -4} },
	{ .states.n = 8, .states.states = {5, 4, 3, 2, -3, 1, -2, -1} },
	{ .states.n = 1, .states.states = {-2} },
	{ .states.n = 1, .states.states = {-1} },
	{ .states.n = 1, .states.states = {0} },
	{ .states.n = 1, .states.states = {1} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 3, .states.states = {4, -4, 2} },
	{ .states.n = 3, .states.states = {5, 3, -3} },
	{ .states.n = 4, .states.states = {6, 4, 2, -2} },
	{ .states.n = 5, .states.states = {7, 5, 3, 1, -1} },
	{ .states.n = 1, .states.states = {0} },
	{ .states.n = 1, .states.states = {1} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 3, .states.states = {4, 3, 2} },
	{ .states.n = 4, .states.states = {5, 4, 3, 2} },
	{ .states.n = 3, .states.states = {6, 3, 2} },
	{ .states.n = 5, .states.states = {7, 6, 4, 3, 2} },
	{ .states.n = 2, .states.states = {3, 2} },
	{ .states.n = 2, .states.states = {3, 2} },
	{ .states.n = 2, .states.states = {3, 2} },
	{ .states.n = 2, .states.states = {2, 1} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 2, .states.states = {4, 2} },
	{ .states.n = 3, .states.states = {5, 3, -3} },
	{ .states.n = 3, .states.states = {6, 4, -2} },
	{ .states.n = 5, .states.states = {7, 5, 3, 1, -1} },
	{ .states.n = 1, .states.states = {0} },
	{ .states.n = 1, .states.states = {1} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 1, .states.states = {4} },
	{ .states.n = 2, .states.states = {5, 3} },
	{ .states.n = 5, .states.states = {6, 5, 4, 3, 2} },
	{ .states.n = 3, .states.states = {7, 6, 4} },
	{ .states.n = 5, .states.states = {8, 6, 4, 3, 2} },
	{ .states.n = 5, .states.states = {5, 4, 3, 2, 1} },
	{ .states.n = 2, .states.states = {4, 2} },
	{ .states.n = 2, .states.states = {2, 1} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 2, .states.states = {4, 2} },
	{ .states.n = 3, .states.states = {5, 3, -3} },
	{ .states.n = 3, .states.states = {6, 4, -2} },
	{ .states.n = 4, .states.states = {7, 5, 1, -1} },
	{ .states.n = 1, .states.states = {0} },
	{ .states.n = 1, .states.states = {1} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 2, .states.states = {4, 3} },
	{ .states.n = 2, .states.states = {4, 3} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 2, .states.states = {3, 2} },
	{ .states.n = 2, .states.states = {3, 2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 2, .states.states = {4, 3} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 2, .states.states = {3, 2} },
	{ .states.n = 2, .states.states = {3, 2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 1, .states.states = {4} },
	{ .states.n = 1, .states.states = {5} },
	{ .states.n = 6, .states.states = {6, 5, 4, 3, 2, 0} },
	{ .states.n = 5, .states.states = {5, 4, 3, 2, -1} },
	{ .states.n = 7, .states.states = {8, 6, 4, 3, 2, 0, -2} },
	{ .states.n = 7, .states.states = {6, 4, 3, 2, 1, 0, -1} },
	{ .states.n = 3, .states.states = {4, 2, 0} },
	{ .states.n = 2, .states.states = {3, 1} },
	{ .states.n = 2, .states.states = {2, 1} },
	{ .states.n = 2, .states.states = {3, 1} },
	{ .states.n = 2, .states.states = {4, 2} },
	{ .states.n = 2, .states.states = {5, 3} },
	{ .states.n = 3, .states.states = {6, 4, 2} },
	{ .states.n = 5, .states.states = {7, 5, 3, 1, -1} },
	{ .states.n = 1, .states.states = {} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 1, .states.states = {4} },
	{ .states.n = 2, .states.states = {5, 4} },
	{ .states.n = 4, .states.states = {6, 5, 4, 3} },
	{ .states.n = 4, .states.states = {6, 5, 4, 3} },
	{ .states.n = 4, .states.states = {6, 5, 4, 3} },
	{ .states.n = 4, .states.states = {6, 5, 4, 3} },
	{ .states.n = 2, .states.states = {4, 3} },
	{ .states.n = 2, .states.states = {4, 3} },
	{ .states.n = 2, .states.states = {4, 3} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 2, .states.states = {3, 2} },
	{ .states.n = 1, .states.states = {3} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
	{ .states.n = 0, .states.states = {} },
};
